// Code generated by sqlc. DO NOT EDIT.

package store

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/google/uuid"
)

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, created_at
FROM users
WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(&i.ID, &i.Phone, &i.CreatedAt)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (id, phone)
VALUES ($1, $2)
RETURNING id, phone, created_at
`

type InsertUserParams struct {
	ID    string
	Phone string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, insertUser, arg.ID, arg.Phone)
	var i User
	err := row.Scan(&i.ID, &i.Phone, &i.CreatedAt)
	return i, err
}

const insertToken = `-- name: InsertToken :one
INSERT INTO auth_tokens (jti, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING jti, user_id, expires_at, created_at
`

type InsertTokenParams struct {
	Jti       uuid.UUID
	UserID    string
	ExpiresAt sql.NullTime
}

func (q *Queries) InsertToken(ctx context.Context, arg InsertTokenParams) (AuthToken, error) {
	row := q.db.QueryRowContext(ctx, insertToken, arg.Jti, arg.UserID, arg.ExpiresAt)
	var i AuthToken
	err := row.Scan(&i.Jti, &i.UserID, &i.ExpiresAt, &i.CreatedAt)
	return i, err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :execresult
DELETE FROM auth_tokens
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredTokens)
	if err != nil {
		return 0, err
	}
	rows, err := result.RowsAffected()
	if err != nil {
		return 0, fmt.Errorf("rows affected: %w", err)
	}
	return rows, nil
}

const getTokenByJTI = `-- name: GetTokenByJTI :one
SELECT jti, user_id, expires_at, created_at
FROM auth_tokens
WHERE jti = $1
`

func (q *Queries) GetTokenByJTI(ctx context.Context, jti uuid.UUID) (AuthToken, error) {
	row := q.db.QueryRowContext(ctx, getTokenByJTI, jti)
	var i AuthToken
	err := row.Scan(&i.Jti, &i.UserID, &i.ExpiresAt, &i.CreatedAt)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone, display_name, created_at
FROM users
WHERE id = $1
`

// GetUserByID fetches the user row by primary key. Used by
// internal/users (PATCH /v1/users/me) to materialize the public
// user view.
func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var u User
	err := row.Scan(&u.ID, &u.Phone, &u.DisplayName, &u.CreatedAt)
	return u, err
}
