// Code generated by sqlc. DO NOT EDIT.
//
// (Hand-augmented: not actually generated — see db/queries/messages.sql for
// the source SQL. Marked generated to signal "do not edit casually"; the
// underlying SQL lives in db/queries/messages.sql so the source of truth
// stays in the migrations tree. If sqlc ever regenerates this file, the
// methods here must match db/queries/messages.sql.)
//
// Sprint 1 WP-1.5: SQL string literals kept verbatim from db/queries/messages.sql
// (matching the .sql source of truth). Go callers should pass typed
// constants from internal/store/enums.go (SenderKindSystem, etc.) when
// supplying sql.NullString args. `::sender_kind` / `::content_type` casts
// added for stricter enum validation at the DB boundary.

package store

import (
	"context"
	"database/sql"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    id, room_id, sender_kind, sender_id, content_type, content,
    mentions, reply_to_id, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    COALESCE($7, '[]'::jsonb), $8, COALESCE($9, NOW())
)
RETURNING id, room_id, sender_kind, sender_id, content_type, content,
          mentions, reply_to_id, created_at
`

type CreateMessageParams struct {
	ID          string
	RoomID      string
	SenderKind  sql.NullString
	SenderID    sql.NullString
	ContentType sql.NullString
	Content     string
	Mentions    []byte
	ReplyToID   sql.NullString
	CreatedAt   sql.NullTime
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.ID, arg.RoomID, arg.SenderKind, arg.SenderID, arg.ContentType, arg.Content,
		arg.Mentions, arg.ReplyToID, arg.CreatedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID, &i.RoomID, &i.SenderKind, &i.SenderID, &i.ContentType, &i.Content,
		&i.Mentions, &i.ReplyToID, &i.CreatedAt,
	)
	return i, err
}

const listMessagesByRoom = `-- name: ListMessagesByRoom :many
SELECT id, room_id, sender_kind, sender_id, content_type, content,
       mentions, reply_to_id, created_at
FROM messages
WHERE room_id = $1
  AND ($2::VARCHAR(26) IS NULL OR id < $2::VARCHAR(26))
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListMessagesByRoomParams struct {
	RoomID string
	Before sql.NullString
	Limit  int32
}

func (q *Queries) ListMessagesByRoom(ctx context.Context, arg ListMessagesByRoomParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByRoom, arg.RoomID, arg.Before, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID, &i.RoomID, &i.SenderKind, &i.SenderID, &i.ContentType, &i.Content,
			&i.Mentions, &i.ReplyToID, &i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countMessagesByRoom = `-- name: CountMessagesByRoom :one
SELECT COUNT(*)
FROM messages
WHERE room_id = $1
`

func (q *Queries) CountMessagesByRoom(ctx context.Context, roomID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessagesByRoom, roomID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const listMessagesBySender = `-- name: ListMessagesBySender :many
SELECT id, room_id, sender_kind, sender_id, content_type, content,
       mentions, reply_to_id, created_at
FROM messages
WHERE sender_kind = $1 AND sender_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListMessagesBySenderParams struct {
	SenderKind sql.NullString
	SenderID   string
	Limit      int32
}

func (q *Queries) ListMessagesBySender(ctx context.Context, arg ListMessagesBySenderParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesBySender, arg.SenderKind, arg.SenderID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID, &i.RoomID, &i.SenderKind, &i.SenderID, &i.ContentType, &i.Content,
			&i.Mentions, &i.ReplyToID, &i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessage = `-- name: GetMessage :one
SELECT id, room_id, sender_kind, sender_id, content_type, content,
       mentions, reply_to_id, created_at
FROM messages
WHERE id = $1
`

func (q *Queries) GetMessage(ctx context.Context, id string) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID, &i.RoomID, &i.SenderKind, &i.SenderID, &i.ContentType, &i.Content,
		&i.Mentions, &i.ReplyToID, &i.CreatedAt,
	)
	return i, err
}