// Code generated by sqlc. DO NOT EDIT.

package store

import (
	"database/sql"

	"github.com/google/uuid"
)

// User is the users table row. ID is the canonical 26-char ULID string
// (ADR-0014) — see auth.Issue + handler.resolveUserID for the
// generation side.
type User struct {
	ID        string
	Phone     string
	CreatedAt sql.NullTime
}

type AuthToken struct {
	Jti       uuid.UUID
	UserID    string
	ExpiresAt sql.NullTime
	CreatedAt sql.NullTime
}