// Code generated by sqlc. DO NOT EDIT.

package store

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID        int64
	Phone     string
	CreatedAt sql.NullTime
}

type AuthToken struct {
	Jti       uuid.UUID
	UserID    int64
	ExpiresAt sql.NullTime
	CreatedAt sql.NullTime
}