// Code generated by sqlc. DO NOT EDIT.
//
// (Hand-augmented: not actually generated — see db/queries/participants.sql
// for the source SQL. Marked generated to signal "do not edit casually";
// the underlying SQL lives in db/queries/participants.sql so the source
// of truth stays in the migrations tree. If sqlc ever regenerates this
// file, the methods here must match db/queries/participants.sql.)

package store

import (
	"context"
	"time"
)

const joinRoom = `-- name: JoinRoom :one
INSERT INTO participants (id, room_id, user_id, stage_state, joined_at)
VALUES ($1, $2, $3, 'on_stage', NOW())
RETURNING id, room_id, user_id, stage_state, joined_at, left_at
`

type JoinRoomParams struct {
	ID     string
	RoomID string
	UserID string
}

func (q *Queries) JoinRoom(ctx context.Context, arg JoinRoomParams) (Participant, error) {
	row := q.db.QueryRowContext(ctx, joinRoom, arg.ID, arg.RoomID, arg.UserID)
	var i Participant
	err := row.Scan(&i.ID, &i.RoomID, &i.UserID, &i.StageState, &i.JoinedAt, &i.LeftAt)
	return i, err
}

const leaveRoom = `-- name: LeaveRoom :execresult
UPDATE participants
SET stage_state = 'off_stage', left_at = NOW()
WHERE room_id = $1 AND user_id = $2 AND stage_state = 'on_stage'
`

type LeaveRoomParams struct {
	RoomID string
	UserID string
}

func (q *Queries) LeaveRoom(ctx context.Context, arg LeaveRoomParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, leaveRoom, arg.RoomID, arg.UserID)
	if err != nil {
		return 0, err
	}
	rows, err := result.RowsAffected()
	if err != nil {
		return 0, err
	}
	return rows, nil
}

const listOnStageByRoom = `-- name: ListOnStageByRoom :many
SELECT id, room_id, user_id, stage_state, joined_at, left_at
FROM participants
WHERE room_id = $1 AND stage_state = 'on_stage'
ORDER BY joined_at ASC
`

func (q *Queries) ListOnStageByRoom(ctx context.Context, roomID string) ([]Participant, error) {
	rows, err := q.db.QueryContext(ctx, listOnStageByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participant
	for rows.Next() {
		var i Participant
		if err := rows.Scan(&i.ID, &i.RoomID, &i.UserID, &i.StageState, &i.JoinedAt, &i.LeftAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listByRoom = `-- name: ListByRoom :many
SELECT id, room_id, user_id, stage_state, joined_at, left_at
FROM participants
WHERE room_id = $1
ORDER BY joined_at DESC
`

func (q *Queries) ListByRoom(ctx context.Context, roomID string) ([]Participant, error) {
	rows, err := q.db.QueryContext(ctx, listByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participant
	for rows.Next() {
		var i Participant
		if err := rows.Scan(&i.ID, &i.RoomID, &i.UserID, &i.StageState, &i.JoinedAt, &i.LeftAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOnStageByUser = `-- name: ListOnStageByUser :many
SELECT id, room_id, user_id, stage_state, joined_at, left_at
FROM participants
WHERE user_id = $1 AND stage_state = 'on_stage'
`

func (q *Queries) ListOnStageByUser(ctx context.Context, userID string) ([]Participant, error) {
	rows, err := q.db.QueryContext(ctx, listOnStageByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participant
	for rows.Next() {
		var i Participant
		if err := rows.Scan(&i.ID, &i.RoomID, &i.UserID, &i.StageState, &i.JoinedAt, &i.LeftAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOnStageParticipant = `-- name: GetOnStageParticipant :one
SELECT id, room_id, user_id, stage_state, joined_at, left_at
FROM participants
WHERE room_id = $1 AND user_id = $2 AND stage_state = 'on_stage'
`

type GetOnStageParticipantParams struct {
	RoomID string
	UserID string
}

func (q *Queries) GetOnStageParticipant(ctx context.Context, arg GetOnStageParticipantParams) (Participant, error) {
	row := q.db.QueryRowContext(ctx, getOnStageParticipant, arg.RoomID, arg.UserID)
	var i Participant
	err := row.Scan(&i.ID, &i.RoomID, &i.UserID, &i.StageState, &i.JoinedAt, &i.LeftAt)
	return i, err
}

// Compile-time guard against time import drift if the methods above
// become empty after a future refactor.
var _ = time.Now