// Code generated by sqlc. DO NOT EDIT.
//
// (Hand-augmented: not actually generated — see db/queries/participants.sql
// for the source SQL. Marked generated to signal "do not edit casually";
// the underlying SQL lives in db/queries/participants.sql so the source
// of truth stays in the migrations tree. If sqlc ever regenerates this
// file, the methods here must match db/queries/participants.sql.)
//
// Sprint 1 WP-1.5: SQL string literals kept verbatim from
// db/queries/participants.sql (matching the .sql source of truth). Go
// callers should pass typed constants from internal/store/enums.go when
// supplying sql.NullString args. `::stage_state` cast added for
// stricter enum validation at the DB boundary.

package store

import (
	"context"
)

// Atomic insert: capacity check ($4) + partial UNIQUE index in one
// statement. Returns sql.ErrNoRows on capacity miss OR duplicate.
//
// Follow-up fix (commit pending): added explicit ::CHAR(26) / ::INT /
// ::stage_state casts on every parameter and literal. Without them
// Postgres returns SQLSTATE 42P08 ("inconsistent types deduced for
// parameter $2") because the same $2 parameter is reused in two
// contexts and the $4 int is ambiguous (int vs bigint). Mirrors the
// ::enum_type cast pattern established in commit `ffdbea4`.
const joinRoom = `-- name: JoinRoom :one
INSERT INTO participants (id, room_id, user_id, stage_state, joined_at)
SELECT $1::CHAR(26),
       $2::CHAR(26),
       $3::CHAR(26),
       'on_stage'::stage_state,
       NOW()
WHERE (SELECT COUNT(*) FROM participants
       WHERE room_id = $2::CHAR(26)
         AND stage_state = 'on_stage'::stage_state) < $4::INT
ON CONFLICT (room_id, user_id) WHERE stage_state = 'on_stage' DO NOTHING
RETURNING id, room_id, user_id, stage_state, joined_at, left_at
`

// MaxParticipants is the rooms.max_participants cap; the SQL refuses the
// INSERT atomically if current on_stage count >= this value.
type JoinRoomParams struct {
	ID              string
	RoomID          string
	UserID          string
	MaxParticipants int32
}

func (q *Queries) JoinRoom(ctx context.Context, arg JoinRoomParams) (Participant, error) {
	row := q.db.QueryRowContext(ctx, joinRoom, arg.ID, arg.RoomID, arg.UserID, arg.MaxParticipants)
	var i Participant
	err := row.Scan(&i.ID, &i.RoomID, &i.UserID, &i.StageState, &i.JoinedAt, &i.LeftAt)
	return i, err
}

// RETURNING the row directly — caller gets the updated row in one
// round trip; sql.ErrNoRows means the user was not on_stage.
//
// Type casts ($1/$2 -> CHAR(26), 'on_stage' -> stage_state) for
// symmetry with JoinRoom.
const leaveRoom = `-- name: LeaveRoom :one
UPDATE participants
SET stage_state = 'off_stage'::stage_state, left_at = NOW()
WHERE room_id = $1::CHAR(26)
  AND user_id = $2::CHAR(26)
  AND stage_state = 'on_stage'::stage_state
RETURNING id, room_id, user_id, stage_state, joined_at, left_at
`

type LeaveRoomParams struct {
	RoomID string
	UserID string
}

func (q *Queries) LeaveRoom(ctx context.Context, arg LeaveRoomParams) (Participant, error) {
	row := q.db.QueryRowContext(ctx, leaveRoom, arg.RoomID, arg.UserID)
	var i Participant
	err := row.Scan(&i.ID, &i.RoomID, &i.UserID, &i.StageState, &i.JoinedAt, &i.LeftAt)
	return i, err
}

const listOnStageByRoom = `-- name: ListOnStageByRoom :many
SELECT id, room_id, user_id, stage_state, joined_at, left_at
FROM participants
WHERE room_id = $1 AND stage_state = 'on_stage'::stage_state
ORDER BY joined_at ASC
`

func (q *Queries) ListOnStageByRoom(ctx context.Context, roomID string) ([]Participant, error) {
	rows, err := q.db.QueryContext(ctx, listOnStageByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participant
	for rows.Next() {
		var i Participant
		if err := rows.Scan(&i.ID, &i.RoomID, &i.UserID, &i.StageState, &i.JoinedAt, &i.LeftAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listByRoom = `-- name: ListByRoom :many
SELECT id, room_id, user_id, stage_state, joined_at, left_at
FROM participants
WHERE room_id = $1
ORDER BY joined_at DESC
`

func (q *Queries) ListByRoom(ctx context.Context, roomID string) ([]Participant, error) {
	rows, err := q.db.QueryContext(ctx, listByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participant
	for rows.Next() {
		var i Participant
		if err := rows.Scan(&i.ID, &i.RoomID, &i.UserID, &i.StageState, &i.JoinedAt, &i.LeftAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOnStageByUser = `-- name: ListOnStageByUser :many
SELECT id, room_id, user_id, stage_state, joined_at, left_at
FROM participants
WHERE user_id = $1 AND stage_state = 'on_stage'::stage_state
`

func (q *Queries) ListOnStageByUser(ctx context.Context, userID string) ([]Participant, error) {
	rows, err := q.db.QueryContext(ctx, listOnStageByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participant
	for rows.Next() {
		var i Participant
		if err := rows.Scan(&i.ID, &i.RoomID, &i.UserID, &i.StageState, &i.JoinedAt, &i.LeftAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOnStageParticipant = `-- name: GetOnStageParticipant :one
SELECT id, room_id, user_id, stage_state, joined_at, left_at
FROM participants
WHERE room_id = $1 AND user_id = $2 AND stage_state = 'on_stage'::stage_state
`

type GetOnStageParticipantParams struct {
	RoomID string
	UserID string
}

func (q *Queries) GetOnStageParticipant(ctx context.Context, arg GetOnStageParticipantParams) (Participant, error) {
	row := q.db.QueryRowContext(ctx, getOnStageParticipant, arg.RoomID, arg.UserID)
	var i Participant
	err := row.Scan(&i.ID, &i.RoomID, &i.UserID, &i.StageState, &i.JoinedAt, &i.LeftAt)
	return i, err
}