// Code generated by sqlc. DO NOT EDIT.
//
// Hand-augmented for Sprint 1 WP-1: added the rooms / participants / messages
// / display_name methods. Source SQL lives in db/queries/*.sql. If sqlc
// regenerates this file, the methods must match those SQL files.

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Sprint 0/1-1/1-2/1-3 (users + auth_tokens)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (int64, error)
	GetRefreshToken(ctx context.Context, jti string) (RefreshToken, error)
	MarkRefreshTokenReplaced(ctx context.Context, jti, replacedBy string) (int64, error)
	DeleteRefreshToken(ctx context.Context, jti string) (int64, error)
	DeleteRefreshFamily(ctx context.Context, familyID string) (int64, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	InsertToken(ctx context.Context, arg InsertTokenParams) (AuthToken, error)
	DeleteExpiredTokens(ctx context.Context) (int64, error)
	GetTokenByJTI(ctx context.Context, jti uuid.UUID) (AuthToken, error)

	// Sprint 1 WP-1 (rooms)
	CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error)
	GetRoom(ctx context.Context, id string) (Room, error)
	ListActiveRooms(ctx context.Context, limit int32) ([]Room, error)
	ListActiveRoomsByHost(ctx context.Context, hostUserID string) ([]Room, error)
	EndRoom(ctx context.Context, id string) (int64, error)
	CountOnStageParticipants(ctx context.Context, roomID string) (int64, error)

	// Sprint 1 WP-1 (participants)
	JoinRoom(ctx context.Context, arg JoinRoomParams) (Participant, error)
	LeaveRoom(ctx context.Context, arg LeaveRoomParams) (Participant, error)
	ListOnStageByRoom(ctx context.Context, roomID string) ([]Participant, error)
	ListByRoom(ctx context.Context, roomID string) ([]Participant, error)
	ListOnStageByUser(ctx context.Context, userID string) ([]Participant, error)
	GetOnStageParticipant(ctx context.Context, arg GetOnStageParticipantParams) (Participant, error)

	// Sprint 1 WP-1 (messages)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	ListMessagesByRoom(ctx context.Context, arg ListMessagesByRoomParams) ([]Message, error)
	CountMessagesByRoom(ctx context.Context, roomID string) (int64, error)
	ListMessagesBySender(ctx context.Context, arg ListMessagesBySenderParams) ([]Message, error)
	GetMessage(ctx context.Context, id string) (Message, error)

	// Sprint 1 WP-1 (users.display_name)
	UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (int64, error)
	GetDisplayName(ctx context.Context, id string) (string, error)

	// Sprint 1-3 (room_agents)
	GetRoomAgent(ctx context.Context, roomID string, agentID string) (RoomAgent, error)
	ListRoomAgentsByRoom(ctx context.Context, roomID string) ([]RoomAgent, error)
	UpsertRoomAgent(ctx context.Context, arg UpsertRoomAgentParams) error
	DeleteRoomAgent(ctx context.Context, roomID string, agentID string) (int64, error)
	DeleteRoomAgentsByRoom(ctx context.Context, roomID string) (int64, error)
}

var _ Querier = (*Queries)(nil)
