// Code generated by sqlc. DO NOT EDIT.

package store

import (
	"context"
)

type Querier interface {
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	InsertToken(ctx context.Context, arg InsertTokenParams) (AuthToken, error)
	DeleteExpiredTokens(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)