// Code generated by sqlc. DO NOT EDIT.
//
// (Hand-augmented: not actually generated — see db/queries/refresh_tokens.sql
// for the source SQL. Marked generated to signal "do not edit casually";
// the underlying SQL lives in db/queries/refresh_tokens.sql. If sqlc
// ever regenerates this file, the methods here must match that file.)

package store

import (
	"context"
	"database/sql"
)

type RefreshToken struct {
	JTI            string
	UserID         string
	FamilyID       string
	ExpiresAt      sql.NullTime
	ReplacedByJTI  sql.NullString
	CreatedAt      sql.NullTime
}

const insertRefreshToken = `-- name: InsertRefreshToken :execresult
INSERT INTO refresh_tokens (jti, user_id, family_id, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertRefreshTokenParams struct {
	JTI       string
	UserID    string
	FamilyID  string
	ExpiresAt sql.NullTime
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertRefreshToken, arg.JTI, arg.UserID, arg.FamilyID, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	rows, err := result.RowsAffected()
	if err != nil {
		return 0, err
	}
	return rows, nil
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT jti, user_id, family_id, expires_at, replaced_by_jti, created_at
FROM refresh_tokens
WHERE jti = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, jti string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, jti)
	var t RefreshToken
	err := row.Scan(&t.JTI, &t.UserID, &t.FamilyID, &t.ExpiresAt, &t.ReplacedByJTI, &t.CreatedAt)
	return t, err
}

const markRefreshTokenReplaced = `-- name: MarkRefreshTokenReplaced :execresult
UPDATE refresh_tokens
SET replaced_by_jti = $2
WHERE jti = $1 AND replaced_by_jti IS NULL
`

func (q *Queries) MarkRefreshTokenReplaced(ctx context.Context, jti, replacedBy string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markRefreshTokenReplaced, jti, replacedBy)
	if err != nil {
		return 0, err
	}
	rows, err := result.RowsAffected()
	if err != nil {
		return 0, err
	}
	return rows, nil
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :execresult
DELETE FROM refresh_tokens WHERE jti = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, jti string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRefreshToken, jti)
	if err != nil {
		return 0, err
	}
	rows, err := result.RowsAffected()
	if err != nil {
		return 0, err
	}
	return rows, nil
}


const deleteRefreshFamily = `-- name: DeleteRefreshFamily :execresult
DELETE FROM refresh_tokens WHERE family_id = $1
`

func (q *Queries) DeleteRefreshFamily(ctx context.Context, familyID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRefreshFamily, familyID)
	if err != nil {
		return 0, err
	}
	rows, err := result.RowsAffected()
	if err != nil {
		return 0, err
	}
	return rows, nil
}
