// Code generated by sqlc. DO NOT EDIT.
//
// (Hand-augmented: not actually generated — see db/queries/room_agents.sql
// for the source SQL. Same convention as messages.go / rooms.go: SQL
// string literals kept verbatim from db/queries/room_agents.sql. sqlc
// v1.31.1 cannot regenerate this repo's store package cleanly, so the
// four methods here are hand-written to match that .sql source of
// truth.)

package store

import (
	"context"
	"time"
)

// RoomAgent is the room_agents table row
// (db/migrations/0009_room_agents.up.sql + 0010_room_agents_multi.up.sql +
// 0011_agent_presets.up.sql): one row per (room, agent) carrying the system
// prompt and cooldown set at invite time. AgentPresetID references a
// persisted agent preset (issue #38); empty = legacy in-room prompt.
type RoomAgent struct {
	RoomID          string
	AgentID         string
	SystemPrompt    string
	CooldownSeconds int32
	AgentPresetID   string
	CreatedAt       time.Time
}

const getRoomAgent = `-- name: GetRoomAgent :one
SELECT room_id, agent_id, system_prompt, cooldown_seconds, agent_preset_id, created_at
FROM room_agents
WHERE room_id = $1 AND agent_id = $2
`

func (q *Queries) GetRoomAgent(ctx context.Context, roomID string, agentID string) (RoomAgent, error) {
	row := q.db.QueryRowContext(ctx, getRoomAgent, roomID, agentID)
	var i RoomAgent
	err := row.Scan(&i.RoomID, &i.AgentID, &i.SystemPrompt, &i.CooldownSeconds, &i.AgentPresetID, &i.CreatedAt)
	return i, err
}

const listRoomAgentsByRoom = `-- name: ListRoomAgentsByRoom :many
SELECT room_id, agent_id, system_prompt, cooldown_seconds, agent_preset_id, created_at
FROM room_agents
WHERE room_id = $1
`

func (q *Queries) ListRoomAgentsByRoom(ctx context.Context, roomID string) ([]RoomAgent, error) {
	rows, err := q.db.QueryContext(ctx, listRoomAgentsByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomAgent
	for rows.Next() {
		var i RoomAgent
		if err := rows.Scan(&i.RoomID, &i.AgentID, &i.SystemPrompt, &i.CooldownSeconds, &i.AgentPresetID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const upsertRoomAgent = `-- name: UpsertRoomAgent :exec
INSERT INTO room_agents (room_id, agent_id, system_prompt, cooldown_seconds, agent_preset_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (room_id, agent_id) DO UPDATE
SET system_prompt = EXCLUDED.system_prompt,
    cooldown_seconds = EXCLUDED.cooldown_seconds,
    agent_preset_id = EXCLUDED.agent_preset_id
`

type UpsertRoomAgentParams struct {
	RoomID          string
	AgentID         string
	SystemPrompt    string
	CooldownSeconds int32
	AgentPresetID   string
}

func (q *Queries) UpsertRoomAgent(ctx context.Context, arg UpsertRoomAgentParams) error {
	_, err := q.db.ExecContext(ctx, upsertRoomAgent, arg.RoomID, arg.AgentID, arg.SystemPrompt, arg.CooldownSeconds, arg.AgentPresetID)
	return err
}

const deleteRoomAgent = `-- name: DeleteRoomAgent :exec
DELETE FROM room_agents
WHERE room_id = $1 AND agent_id = $2
`

func (q *Queries) DeleteRoomAgent(ctx context.Context, roomID string, agentID string) (int64, error) {
	res, err := q.db.ExecContext(ctx, deleteRoomAgent, roomID, agentID)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}

const deleteRoomAgentsByRoom = `-- name: DeleteRoomAgentsByRoom :exec
DELETE FROM room_agents
WHERE room_id = $1
`

func (q *Queries) DeleteRoomAgentsByRoom(ctx context.Context, roomID string) (int64, error) {
	res, err := q.db.ExecContext(ctx, deleteRoomAgentsByRoom, roomID)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}
