// Code generated by sqlc. DO NOT EDIT.
//
// (Hand-augmented: not actually generated — see db/queries/rooms.sql for
// the source SQL. Marked generated to signal "do not edit casually"; the
// underlying SQL lives in db/queries/rooms.sql so the source of truth
// stays in the migrations tree. If sqlc ever regenerates this file, the
// methods here must match db/queries/rooms.sql.)
//
// Sprint 1 WP-1.5: SQL string literals kept verbatim from db/queries/rooms.sql
// (matching the .sql source of truth). Go callers should pass the typed
// constants from internal/store/enums.go (RoomStatusActive, etc.) when
// supplying sql.NullString args.

package store

import (
	"context"
	"database/sql"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (
    id, host_user_id, name, max_participants, keep_messages_on_end,
    status, announcement, created_at, ended_at
) VALUES (
    $1, $2, $3, $4, $5,
    COALESCE($6, 'active'::room_status), COALESCE($7, ''), COALESCE($8, NOW()), $9
)
RETURNING id, host_user_id, name, max_participants, keep_messages_on_end,
          status, announcement, created_at, ended_at
`

type CreateRoomParams struct {
	ID                string
	HostUserID        string
	Name              string
	MaxParticipants   int32
	KeepMessagesOnEnd bool
	Status            sql.NullString
	Announcement      sql.NullString
	CreatedAt         sql.NullTime
	EndedAt           sql.NullTime
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRowContext(ctx, createRoom,
		arg.ID, arg.HostUserID, arg.Name, arg.MaxParticipants, arg.KeepMessagesOnEnd,
		arg.Status, arg.Announcement, arg.CreatedAt, arg.EndedAt,
	)
	var i Room
	err := row.Scan(
		&i.ID, &i.HostUserID, &i.Name, &i.MaxParticipants, &i.KeepMessagesOnEnd,
		&i.Status, &i.Announcement, &i.CreatedAt, &i.EndedAt,
	)
	return i, err
}

const getRoom = `-- name: GetRoom :one
SELECT id, host_user_id, name, max_participants, keep_messages_on_end,
       status, announcement, created_at, ended_at
FROM rooms
WHERE id = $1
`

func (q *Queries) GetRoom(ctx context.Context, id string) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID, &i.HostUserID, &i.Name, &i.MaxParticipants, &i.KeepMessagesOnEnd,
		&i.Status, &i.Announcement, &i.CreatedAt, &i.EndedAt,
	)
	return i, err
}

const listActiveRooms = `-- name: ListActiveRooms :many
SELECT id, host_user_id, name, max_participants, keep_messages_on_end,
       status, announcement, created_at, ended_at
FROM rooms
WHERE status = 'active'::room_status
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListActiveRooms(ctx context.Context, limit int32) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRooms, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID, &i.HostUserID, &i.Name, &i.MaxParticipants, &i.KeepMessagesOnEnd,
			&i.Status, &i.Announcement, &i.CreatedAt, &i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveRoomsByHost = `-- name: ListActiveRoomsByHost :many
SELECT id, host_user_id, name, max_participants, keep_messages_on_end,
       status, announcement, created_at, ended_at
FROM rooms
WHERE host_user_id = $1 AND status = 'active'::room_status
ORDER BY created_at DESC
`

func (q *Queries) ListActiveRoomsByHost(ctx context.Context, hostUserID string) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRoomsByHost, hostUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID, &i.HostUserID, &i.Name, &i.MaxParticipants, &i.KeepMessagesOnEnd,
			&i.Status, &i.Announcement, &i.CreatedAt, &i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const endRoom = `-- name: EndRoom :execresult
UPDATE rooms
SET status = 'ended'::room_status, ended_at = NOW()
WHERE id = $1 AND status = 'active'::room_status
`

func (q *Queries) EndRoom(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, endRoom, id)
	if err != nil {
		return 0, err
	}
	rows, err := result.RowsAffected()
	if err != nil {
		return 0, err
	}
	return rows, nil
}

const countOnStageParticipants = `-- name: CountOnStageParticipants :one
SELECT COUNT(*)
FROM participants
WHERE room_id = $1 AND stage_state = 'on_stage'::stage_state
`

// CountOnStageParticipants returns the number of on_stage participants in
// a room. Used by capacity check before Join. Returns int64 (matches
// COUNT(*) in PG) — callers compare against rooms.max_participants.
func (q *Queries) CountOnStageParticipants(ctx context.Context, roomID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOnStageParticipants, roomID)
	var n int64
	err := row.Scan(&n)
	return n, err
}