// Code generated by sqlc. DO NOT EDIT.
//
// (Hand-augmented: not actually generated — see db/queries/users_display_name.sql
// for the source SQL. Marked generated to signal "do not edit casually";
// the underlying SQL lives in db/queries/users_display_name.sql. If sqlc
// ever regenerates this file, the methods here must match that file.)

package store

import (
	"context"
)

const updateUserDisplayName = `-- name: UpdateUserDisplayName :execresult
UPDATE users
SET display_name = $2
WHERE id = $1
`

type UpdateUserDisplayNameParams struct {
	ID          string
	DisplayName string
}

func (q *Queries) UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateUserDisplayName, arg.ID, arg.DisplayName)
	if err != nil {
		return 0, err
	}
	rows, err := result.RowsAffected()
	if err != nil {
		return 0, err
	}
	return rows, nil
}

const getDisplayName = `-- name: GetDisplayName :one
SELECT display_name
FROM users
WHERE id = $1
`

// GetDisplayName fetches just the display_name column (used by lobby list
// to show host.display_name without pulling the full User row).
func (q *Queries) GetDisplayName(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getDisplayName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}